# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a230b1ab7ac93ed81fe206ffab1f9399f500bdea0b9cfe618567e5861431bf4af6d06be5627a2f4c4606f0560b1c9d3d0dbd5a59aa48ec3bdf9633e32b0b95e

test:
  secret_key_base: 10ba6f835cf8071c13c0e560dfdf1014c5bc11915227afd319a2e198e0a6d16928f292bfecab610acfdfa3c4fd5b1a633e257a257457db1c3d12f0bf7aa5f7e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
